if(!self.__appxInited) {
self.__appxInited = 1;


require('./config$');


var AFAppX = self.AFAppX;
self.getCurrentPages = AFAppX.getCurrentPages;
self.getApp = AFAppX.getApp;
self.Page = AFAppX.Page;
self.App = AFAppX.App;
self.my = AFAppX.bridge || AFAppX.abridge;
self.abridge = self.my;
self.Component = AFAppX.WorkerComponent || function(){};
self.$global = AFAppX.$global;


function success() {
require('../..//app');
require('../../components/nav/nav');
require('../../node_modules/mini-antui/es/badge/index');
require('../../node_modules/mini-antui/es/tabs/index');
require('../../node_modules/mini-antui/es/tabs/tab-content/index');
require('../../components/add-button/add-button');
require('../../node_modules/mini-antui/es/search-bar/index');
require('../../node_modules/mini-antui/es/popup/index');
require('../../node_modules/mini-antui/es/list/index');
require('../../node_modules/mini-antui/es/list/list-item/index');
require('../../node_modules/mini-antui/es/swipe-action/index');
require('../../node_modules/mini-antui/es/modal/index');
require('../../node_modules/mini-antui/es/stepper/index');
require('../../node_modules/mini-antui/es/am-checkbox/index');
require('../../node_modules/mini-antui/es/calendar/index');
require('../../node_modules/mini-antui/es/notice/index');
require('../../pages/index/index');
require('../../pages/todos/todos');
require('../../pages/shop/shoplist/shoplist');
require('../../pages/shop/shopDetail/shopDetail');
require('../../pages/me/me/me');
require('../../pages/order/orderlist/orderlist');
require('../../pages/home/search/search');
require('../../pages/home/extension/extension');
require('../../pages/home/more/more');
require('../../pages/me/setup/setup');
require('../../pages/me/helpCenter/index/index');
require('../../pages/me/helpCenter/help/help');
require('../../pages/me/userinfo/index/index');
require('../../pages/me/userinfo/info/info');
require('../../pages/me/userinfo/security/index/index');
require('../../pages/me/userinfo/security/newpassword/newpassword');
require('../../pages/me/userinfo/security/bindphone/bindphone');
require('../../pages/me/userinfo/security/sendcode/sendcode');
require('../../pages/me/userinfo/security/newphone/newphone');
require('../../pages/me/userinfo/address/addresslist/addresslist');
require('../../pages/me/userinfo/address/addaddress/addaddress');
require('../../pages/me/integral/integral');
require('../../pages/me/integralrule/integralrule');
require('../../pages/me/cart/cart');
require('../../pages/me/coupon/coupon');
require('../../pages/me/myBalance/index/index');
require('../../pages/me/myBalance/cash/cash');
require('../../pages/me/myBalance/bankcard/bankcard');
require('../../pages/me/myBalance/addbankcard/addbankcard');
require('../../pages/me/certification/index/index');
require('../../pages/me/certification/people/people');
require('../../pages/me/certification/addPeople/addPeople');
require('../../pages/me/certification/realname/realname');
require('../../pages/me/certification/realnameSuc/realnameSuc');
require('../../pages/me/certification/realnameUnbundling/realnameUnbundling');
require('../../pages/home/welfareAgency/welfareAgency');
require('../../pages/goodsDetail/goodsDetail');
require('../../pages/home/commitList/commitList');
require('../../pages/hosting/gohosting/index/index');
require('../../pages/hosting/gohosting/steps2/steps2');
require('../../pages/hosting/gohosting/steps3/steps3');
require('../../pages/hosting/gohosting/steps4/steps4');
require('../../pages/login/login/login');
require('../../pages/login/passwordLogin/passwordLogin');
require('../../pages/login/forgetPassword/forgetPassword');
require('../../pages/login/resetPassword/resetPassword');
require('../../pages/login/inputCode/inputCode');
require('../../pages/order/pay/pay');
require('../../pages/buy/buy');
require('../../pages/order/address/addresslist/addresslist');
require('../../pages/order/address/addaddress/addaddress');
require('../../pages/order/people/people');
require('../../pages/order/locationList/locationList');
require('../../pages/order/calendar/calendar');
require('../../pages/order/agreement/agreement');
require('../../pages/hosting/gohosting/successful/successful');
require('../../pages/hosting/myhosting/index/index');
require('../../pages/hosting/myhosting/hostCancel/hostCancel');
require('../../pages/hosting/myhosting/detail/detail');
require('../../pages/hosting/myhosting/nodetail/nodetail');
require('../../pages/hosting/myhosting/pay/pay');
require('../../pages/hosting/myhosting/platformDeli/platformDeli');
require('../../pages/hosting/myhosting/postDeli/postDeli');
require('../../pages/order/buypay/buypay');
require('../../pages/order/comments/comments');
require('../../pages/order/buydetail/buydetail');
require('../../pages/order/buyOrderDetail/buyOrderDetail');
require('../../pages/home/redpacket/redpacket/redpacket');
require('../../pages/home/redpacket/rpfriend/rpfriend');
require('../../pages/order/relet/relet');
require('../../pages/order/compensation/compensation');
require('../../pages/order/deny/deny');
require('../../pages/order/refund/refund');
require('../../pages/order/friendRepay/friendRepay');
require('../../pages/order/appointmentExpress/appointmentExpress');
require('../../pages/order/sendBack/sendBack');
require('../../pages/order/shopping/shopping');
require('../../pages/order/orderDetail/orderDetail');
require('../../pages/home/questionnaire/questionnaire');
require('../../pages/friendBuyShare/friendBuyShare');
require('../../pages/web/web');
}
self.bootstrapApp ? self.bootstrapApp({ success }) : success();
}